### ISSUE TITLE
Uncaught Error: Could not find module `foo-bar/components/foo-bar/template` imported from `foo-bar/components/foo-bar/component`

### ISSUE THREAD

**Issue by eccegordo** [trabus/in-repo-addon-pod-template#1]
FYI, checking this out, then npm install, and then bower install, them ember serve

I get the following error 

```
Uncaught Error: Could not find module `foo-bar/components/foo-bar/template` imported from `foo-bar/components/foo-bar/component`

```

**Comment by trabus** [comment]
Ah, yes, this is because pods aren't supported in addons yet. I forgot that I'd created this repo specifically to illustrate it for this issue: https://github.com/ember-cli/ember-cli/issues/3586
